### ISSUE TITLE
weird format when pages load

### ISSUE THREAD

**Issue by sollago** [marlago/website#38]
Every time that a page on the website loads, the pre-formatted version is briefly displayed, which is quite weird for people to see. Is there a way to prevent the website to show pre-formatted content?

**Comment by iliakur** [comment]
At work we were looking at website performance measuring tools, so I took the opportunity to run one.

Here's its report, will take action on it soon:
https://gtmetrix.com/reports/sollago.github.io/4ZB5JC2Q
