### ISSUE TITLE
Connection not secure problem

### ISSUE THREAD

**Issue by sollago** [marlago/website#52]
When loading the website, the browser has the "i" symbol on the browsing tab indicating that the connection is not secure. I thought that this was an inherent problem in hosting the website on github, but other github pages don't seem to have this problem and are shown as secure (e.g. https://tmalsburg.github.io/). Could this be fixed?

**Comment by iliakur** [comment]
Yes, definitely!
https://help.github.com/articles/securing-your-github-pages-site-with-https/

That page says that you'll have to go and change stuff in settings on github and I'll have to go through the code making sure all internal links are https

**Comment by sollago** [comment]
Cool! I have done my part, by selecting **Enforce HTTPS** in the settings.

**Comment by iliakur** [comment]
The live version of the website isn't loading any of the CSS or JS. I've opened a [PR](#53) to address this.

**Comment by iliakur** [comment]
I think we can close this...
